'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';


import './globals.css';
import './page.module.css';
import styles from './layout.module.css';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const navLinks = [
    { href: '/', label: 'Home' },
    { href: '/feed', label: 'Feed' },
    { href: '/profile', label: 'Profile' },
    { href: '/about', label: 'About' },
    { href: '/contact', label: 'Contact' },
  ];
  return (
    <html lang="en">
      <body>
      <head>
        <title>Title</title>
        <meta name='description' content='Description' />
      </head>
      <header className={styles.header}>
          <h1>My Next.js App</h1>
        </header>
        <nav className={styles.nav}>
          {navLinks.map((link) => (
            <Link
              key={link.href}
              href={link.href}
              className={`${styles.link} ${pathname === link.href ? styles.active : ''}`}
            >
              {link.label}
            </Link>
          ))}
        </nav>

        <main>{children}</main>

        <footer className={styles.footer}>
          <p>© 2025 My Next.js App. All rights reserved.</p>
        </footer>
        
      </body>
    </html>
  )
}
